### PR TITLE
oras version

### LINKED ISSUE #49: oras version command
Command `oras version` should display the current version (eg `v0.3.3`)

### PR DESCRIPTION
**Pull request by shizhMSFT**
Run `oras version` to print the version.
```
$ bin/linux/amd64/oras version
Version:        0.4.0+unreleased
Go version:     go1.11.1
Git commit:     04121d7b0c35b067a1c58dd5ff42a0006358bc76
Git tree state: clean
```

Resolves #49

### CODE REVIEW

**Comment by jdolitsky** [comment]
@bacongobbler the code looks pretty similar - are you just suggesting to add a public `Get()` method vs. having public vars like `Version` etc?

**Comment by bacongobbler** [comment]
No, I'm suggesting moving `pkg/version` to `internal/version`. Helm or other packages can't use this package unless those variables were defined at compile time.

**Pull request merged**
