### PR TITLE
cache docker types too

### LINKED ISSUE #226: hybrid store caching misses docker media types but ChildrenHandler expects them
The caching code is [here](https://github.com/deislabs/oras/blob/a64b0ac4faf26c58016fbd7ed1a9eb9d049e54ee/pkg/oras/store.go#L64-L66):

```go
	if isAllowedMediaType(wOpts.Desc.MediaType, ocispec.MediaTypeImageManifest, ocispec.MediaTypeImageIndex) || s.ingester == nil {
		return s.cache.Writer(ctx, opts...)
	}
```

However, the containerd Children handler [here](https://github.com/containerd/containerd/blob/v1.4.3/images/image.go#L330-L369):

```go
	switch desc.MediaType {
	case MediaTypeDockerSchema2Manifest, ocispec.MediaTypeImageManifest:
		p, err := content.ReadBlob(ctx, provider, desc)
		if err != nil {
			return nil, err
		}

		// TODO(stevvooe): We just assume oci manifest, for now. There may be
		// subtle differences from the docker version.
		var manifest ocispec.Manifest
		if err := json.Unmarshal(p, &manifest); err != nil {
			return nil, err
		}

		descs = append(descs, manifest.Config)
		descs = append(descs, manifest.Layers...)
	case MediaTypeDockerSchema2ManifestList, ocispec.MediaTypeImageIndex:
		p, err := content.ReadBlob(ctx, provider, desc)
		if err != nil {
			return nil, err
		}

		var index ocispec.Index
		if err := json.Unmarshal(p, &index); err != nil {
			return nil, err
		}

		descs = append(descs, index.Manifests...)
	default:
		if IsLayerType(desc.MediaType) || IsKnownConfig(desc.MediaType) {
			// childless data types.
			return nil, nil
		}
		log.G(ctx).Debugf("encountered unknown type %v; children may not be fetched", desc.MediaType)
	}
```

expects the ability to read from the provider (in our case, the cache) for all _four_ media types (OCI manifest and index, docker manifest and manifest list). This means that if we actually do pull down some such from the docker types, it will try to read it, but it isn't cached, and will return a "not found" error.

The simplest solution appears to be to add the two media types - I have a PR about to submit for it - but I am concerned that the lack of passthrough (see #225) might mean this would break something else.

### PR DESCRIPTION
**Pull request by deitch**
Fixes #226 

But worth awaiting the result of #225 before merging in to see any impact.

### CODE REVIEW

**Comment by deitch** [comment]
This is the last of the 3 (I think) PRs to handle the caching issue, discussed with @jdolitsky. We had discussed whether or not we should be adding the legacy docker types, in addition to the OCI types, to the list of types to be cached.

This PR assumes they should. You had suggested at one point to make the OCI types be the default, and have an option to override the types to be cached.

I am ok with that, in principle, but it creates some unanswered questions:

### append vs replace 

Should the option _append_ types, or _replace_ them? 

I think _replace_ is just simpler, especially if we make the default types available via a function that `hybridStore` uses. So if I want to replace, I just replace; if I want to append, I call `getDefaultTypes()` (or whatever) and then just append to the slice, and pass that as a replace.

### where to pass the option

The bigger issue is where to pass this option? It only is relevant to [newHybridStoreFromIngester](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/store.go#L35), which currently does not have options, although we can add them. But `hybridStore` (and `newHybridStoreFrom*()`) are private. [newHybridStoreFromIngester](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/store.go#L35) is called only by [fetchContent](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/pull.go#L47) (again private), which in turn is called by [Pull](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/pull.go#L19).

The only exposed place is [Pull](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/pull.go#L19). We could pass an option there, but that seems distant from what it is dealing with. To have an option to modify how the deep down cache behaves when calling [Pull](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/pull.go#L19) seems a bit disjoint. Then again, we have an option [WithContentProvideIngester](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/pull_opts.go#L78), so perhaps it is fine?

I see three options:

1. Just take this as is. It certainly is the simplest option by far.
2. Create a new func that returns a [PullOpt](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/pull_opts.go#L27), named something like `WithCacheMediaTypes(...MediaType)`
3. Make `hybridStore` public/exported, give it a creation-time option to modify cached types, and then consumers can use [WithContentProvideIngester](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/pull_opts.go#L78)

My obvious personal preference is just this PR. It is by far the simplest (2-line change). Josh, thoughts?

**Comment by deitch** [comment]
This is the last of the 3 (I think) PRs to handle the caching issue, discussed with @jdolitsky. We had discussed whether or not we should be adding the legacy docker types, in addition to the OCI types, to the list of types to be cached.

This PR assumes they should. You had suggested at one point to make the OCI types be the default, and have an option to override the types to be cached.

I am ok with that, in principle, but it creates some unanswered questions:

### append vs replace 

Should the option _append_ types, or _replace_ them? 

I think _replace_ is just simpler, especially if we make the default types available via a function that `hybridStore` uses. So if I want to replace, I just replace; if I want to append, I call `getDefaultTypes()` (or whatever) and then just append to the slice, and pass that as a replace.

### where to pass the option

The bigger issue is where to pass this option? It only is relevant to [newHybridStoreFromIngester](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/store.go#L35), which currently does not have options, although we can add them. But `hybridStore` (and `newHybridStoreFrom*()`) are private. [newHybridStoreFromIngester](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/store.go#L35) is called only by [fetchContent](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/pull.go#L47) (again private), which in turn is called by [Pull](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/pull.go#L19).

The only exposed place is [Pull](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/pull.go#L19). We could pass an option there, but that seems distant from what it is dealing with. To have an option to modify how the deep down cache behaves when calling [Pull](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/pull.go#L19) seems a bit disjoint. Then again, we have an option [WithContentProvideIngester](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/pull_opts.go#L78), so perhaps it is fine?

I see three options:

1. Just take this as is. It certainly is the simplest option by far.
2. Create a new func that returns a [PullOpt](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/pull_opts.go#L27), named something like `WithCacheMediaTypes(...MediaType)`
3. Make `hybridStore` public/exported, give it a creation-time option to modify cached types, and then consumers can use [WithContentProvideIngester](https://github.com/deislabs/oras/blob/75801fef923e9d9945f512494f4790cdf1c022cd/pkg/oras/pull_opts.go#L78)

My obvious personal preference is just this PR. It is by far the simplest (2-line change). Josh, thoughts?

**Comment by jdolitsky** [comment]
@deitch - option 2 is still my preference. This enables oras to be fully agnostic to mediatypes

**Comment by deitch** [comment]
You would want the harder one, wouldn't you? 

Let's see what we can do.

**Comment by deitch** [comment]
@jdolitsky take a look at it now. See if this works.

**Review by jdolitsky — APPROVED** [review]
this looks great

**Comment by deitch** [comment]
I was waiting for you to merge, then realized, wait a sec, I don't need to. I can do it once you approved (which you did) 😃

**Pull request merged**
