### PR TITLE
add logo

### LINKED ISSUE #81: Logo
As we all know, every amazing project needs an amazing logo

### PR DESCRIPTION
**Pull request by jdolitsky**
Fixes #81

### CODE REVIEW

**Comment by shizhMSFT** [comment]
The logo looks similar to a `oreo` logo. Could you make sure the font is properly licensed?

**Comment by jdolitsky** [comment]
Will make an original version based on this

**Comment by jdolitsky** [comment]
@shizhMSFT updated, have a look :)

**Comment by bacongobbler** [comment]
I'm still really concerned that this is very closely related to Mr. Christie's Oreo logo. We should have legal take a look at this just to cover our bases, but I'm fairly certain they won't allow us to accept this logo as-is.

**Comment by jdolitsky** [comment]
This weighs heavily my heart and soul 💔
RIP open source

**Comment by jdolitsky** [comment]
@bacongobbler ok, uploaded a new one that should be legally sound.

Uses the "Action Jackson" font found here: https://www.1001fonts.com/action-jackson-font.html

The font is absolutely free for commercial use, you can scan the license for it here: http://fonts.tom7.com/legal/

Colors scheme based on the Duffle logo :)

**Comment by jdolitsky** [comment]
🎉

**Pull request merged**
