### PR TITLE
oras pull with cache

### LINKED ISSUE #193: Cached ORAS Pull
Customers may pull the same artifact multiple times, or multiple manifests sharing common artifacts.

In order to save the unnecessary network bandwidth and disk I/O. `oras` should provide a solution to pull the artifacts into a local content-address storage (CAS) if the content does not exist, and then copy the artifact to the desired storage. 

The cache directory should be specified by the customers using the environment variable `ORAS_CACHE`. If not specified, cache is not used.

# Proposed user experience
## Fresh Pull
Alice specifies the cache location by `ORAS_CACHE=~/.oras/cache`, and pulls the artifact by `oras pull some.registry.io/target:1.0`.
1. `oras` tries to pull the manifest.
2. Since the target manifest `sha256:05b3abf2579a5eb66403cd78be557fd860633a1fe2103c7642030defe32c657f` does not exist in the cache, `oras` downloads the manifest to `~/.oras/cache/blobs/sha256/05b3abf2579a5eb66403cd78be557fd860633a1fe2103c7642030defe32c657f`.
3. `oras` tries to pull the artifact layer.
4. Since the target artifact `sha256:c7c5c1d70c5dec4416ab6158afd0b223ef40c29b1dc1f97ed9428b94d4cadb1c` does not exist in the cache, `oras` downloads the artifact to `~/.oras/cache/blobs/sha256/c7c5c1d70c5dec4416ab6158afd0b223ef40c29b1dc1f97ed9428b94d4cadb1c`.
5. `oras` copies the artifact in the cache to the local directory with the name specified in the manifest.

## Repeated Pull
Alice specifies the cache location by `ORAS_CACHE=~/.oras/cache`, and pulls the artifact by `oras pull some.registry.io/target:1.0`.
1. `oras` tries to pull the manifest.
2. Since the target manifest `sha256:05b3abf2579a5eb66403cd78be557fd860633a1fe2103c7642030defe32c657f` exists in the cache, `oras` skips downloading the manifest.
3. `oras` tries to pull the artifact layer.
4. Since the target artifact `sha256:c7c5c1d70c5dec4416ab6158afd0b223ef40c29b1dc1f97ed9428b94d4cadb1c` exists in the cache, `oras` skips downloading the artifact.
5. `oras` copies the artifact in the cache to the local directory with the name specified in the manifest.

## Pull with Common Layer
Alice specifies the cache location by `ORAS_CACHE=~/.oras/cache`, and pulls the artifact by `oras pull some.registry.io/target:1.1`.
1. `oras` tries to pull the manifest.
2. Since the target manifest `sha256:e7b0c7ca59efa17fc92e5aafb66a8109dd8bac6baf3db6e56c926dfa263ec1ea` does not exist in the cache, `oras` downloads the manifest to `~/.oras/cache/blobs/sha256/e7b0c7ca59efa17fc92e5aafb66a8109dd8bac6baf3db6e56c926dfa263ec1ea`.
3. `oras` tries to pull the artifact layer.
4. Since the target artifact `sha256:c7c5c1d70c5dec4416ab6158afd0b223ef40c29b1dc1f97ed9428b94d4cadb1c` exists in the cache, `oras` skips downloading the artifact.
5. `oras` copies the artifact in the cache to the local directory with the name specified in the manifest.

### PR DESCRIPTION
**Pull request by shizhMSFT**
Resolves #193. The cache is enabled only when the environment variable `ORAS_CACHE` is set in the CLI.

Example usage:
```bash
# Set cache root
export ORAS_CACHE=~/.oras/cache

# Pull artifacts as usual
oras pull localhost:5000/hello:latest
```

### CODE REVIEW

**Comment by sajayantony** [comment]
Could you please show the layout of the cache?

**Comment by shizhMSFT** [comment]
@sajayantony The cache uses [github.com/containerd/containerd/content/local](https://github.com/containerd/containerd/tree/master/content/local) as its content store.

The layout of the cache is
```
$ORAS_CACHE
├── blobs
│   └── <algorithm>
│       └── <digest>
└── ingest
    └── <ref_digest>
        ├── data
        ├── ref
        ├── startedat
        ├── total
        └── updatedat
```
Note that the `ingest` folder is used only when downloading. After downloading, the `ingest` folder should be empty.

**Comment by jdolitsky** [comment]
Hey, this is great. Does it make sense to include index.json (as in [OCI Layout](https://github.com/opencontainers/image-spec/blob/master/image-layout.md)?)

We have `OCIStore` to manage this file: https://github.com/deislabs/oras/blob/main/pkg/content/oci.go

Can we combine that with the `containerd/local` cache?

**Review by jdolitsky — CHANGES_REQUESTED** [review]
Hey, this is great. Does it make sense to include index.json (as in OCI Layout?)

We have OCIStore to manage this file: https://github.com/deislabs/oras/blob/main/pkg/content/oci.go

Can we combine that with the containerd/local cache?

**Comment by shizhMSFT** [comment]
@jdolitsky The cache store here must be a pure **content-addressable storage** (i.e. no refs) so that the cache can be used by multiple `oras` clients concurrently with no race conditions.

Besides, we are actually caching at the blob level not images. Therefore, it does not make sense to add an index.

**Comment by SteveLasker** [comment]
Josh, are you asking if we can store the manifests? Both image-index and image-manifest, so they are cached and available to compute digests?

**Comment by jdolitsky** [comment]
I'm thinking of Helm here. Had this type of cache (combined with index.json support) had existed, we would not have needed to implemented.. I understand an "oras" pull of reference when working with files does not require saving of the reference (e.g. `localhost:5000/hello:latest`).

This has value as general purpose local CAS, will approve. Later if needed we can make a hybrid store from this and `OCIStore`. @shizhMSFT merge when ready

**Review by jdolitsky — APPROVED** [review]

**Pull request merged**
