### PR TITLE
Update example code

### PR DESCRIPTION
**Pull request by shizhMSFT**
Close `FileStore` as introduced by #55

### CODE REVIEW

**Comment by sajayantony** [comment]
Does pull display the OCI manifest digest? If not could we add this to the output?

**Comment by shizhMSFT** [comment]
> Does pull display the OCI manifest digest? If not could we add this to the output?

OCI manifest digest is not visible outside of `oras` package. To be clear, the `oras` users should not bother how the underlying stuffs work. They only need to care about the files to be pushed or pulled. What's purpose of printing the OCI or the docker manifest digest?

In addition, `oras pull` supports index / manifest list with multiple sub-manifests, although `oras push` does not. Which manifest? or all manifests should we print?

**Comment by sajayantony** [comment]
The PR shows the power of ORAS. The contentment addressability is always through digest and unlike a tag is immutable. 
Docker pull today shows you the tag digest so that you can, you want reference by digest. 
In the index case, I believe it is a index manifest since the tag dereferences to that index.

Also ORAS should highlight content addressability since it’s a library in the pure sense. It’s good to not have the user worry about the digest if not required but ORAS having the ability to obtain/save the manifest and output the digest in a sample will be useful. 
This aligns with docker manifest commands in someway I feel.

**Comment by shizhMSFT** [comment]
@sajayantony Let's continue discussion in #68

**Pull request closed without merging**
